env:
  NODE_VERSION: "18"
  PYTHON_VERSION: "3.11"
  STAGE: "dev"
on:
  workflow_dispatch:
  push:
    branches: [development]
jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-skip-session-tagging: true
          role-session-name: ${{ env.SESSION_NAME }}
        env:
          SESSION_NAME: "github-${{github.sha}}-${{ env.STAGE }}"
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Setup venv
        run: |
          pip install uv
          uv venv
          echo "VIRTUAL_ENV=${Python_ROOT_DIR}" >> "$GITHUB_ENV"
      - name: Install CDK
        run: npm install -g aws-cdk 
      - name: Install dependencies
        run: |
          source .venv/bin/activate
          uv pip install -r requirements.txt -U
      - name: Deploy stack
        run: |
          source .venv/bin/activate
          cdk deploy --all --require-approval never
