env:
  NODE_VERSION: "18"
  PYTHON_VERSION: "3.11"
  STAGE: "dev"
on:
  workflow_dispatch:
  push:
    branches: [development]
jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-skip-session-tagging: true
          role-session-name: ${{ env.SESSION_NAME }}
        env:
          SESSION_NAME: "github-${{github.sha}}-${{ env.STAGE }}"
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install CDK
        run: npm install -g aws-cdk 
      - name: Install dependencies
        run: pip install -r requirements.txt -U --force
      - name: Deploy stack
        run: cdk deploy --all --require-approval never --force
